-- Collecta — schema, indexes, and Row Level Security policies.
-- Run this in the Supabase SQL editor (or via `supabase db push`) on a fresh project.

create extension if not exists "pgcrypto";
create extension if not exists pg_cron with schema extensions;

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------

create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  role text not null check (role in ('freelancer', 'client')),
  name text not null,
  avatar_url text,
  email text not null,
  push_token text,
  theme text not null default 'amber-noir',
  notification_prefs jsonb not null default '{"invoicePaid":true,"paymentReminders":true,"weeklyReport":false,"projectUpdates":true,"marketing":false}'::jsonb,
  -- Freelancer-only setting — pre-fills new invoices and scopes the dashboard
  -- aggregate totals, which can't correctly sum across different currencies.
  default_currency text not null default 'usd',
  created_at timestamptz not null default now()
);

create table public.freelancer_clients (
  id uuid primary key default gen_random_uuid(),
  freelancer_id uuid not null references public.profiles (id) on delete cascade,
  client_id uuid not null references public.profiles (id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (freelancer_id, client_id)
);

create table public.projects (
  id uuid primary key default gen_random_uuid(),
  freelancer_id uuid not null references public.profiles (id) on delete cascade,
  client_id uuid not null references public.profiles (id) on delete cascade,
  title text not null,
  status text not null default 'active' check (status in ('active', 'completed', 'on_hold')),
  created_at timestamptz not null default now()
);

create table public.milestones (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects (id) on delete cascade,
  title text not null,
  status text not null default 'pending' check (status in ('pending', 'complete')),
  due_date date
);

-- A saved recurring-billing schedule (e.g. a monthly retainer) that
-- generate_recurring_invoices() (below) turns into real invoices on its own,
-- via pg_cron — see that function for the generation logic.
create table public.invoice_templates (
  id uuid primary key default gen_random_uuid(),
  freelancer_id uuid not null references public.profiles (id) on delete cascade,
  client_id uuid not null references public.profiles (id) on delete cascade,
  project_id uuid references public.projects (id) on delete set null,
  amount numeric(10, 2) not null check (amount >= 0),
  currency text not null default 'usd',
  interval text not null check (interval in ('weekly', 'monthly', 'quarterly', 'yearly')),
  due_in_days int not null default 14 check (due_in_days >= 0),
  next_run_date date not null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.invoices (
  id uuid primary key default gen_random_uuid(),
  freelancer_id uuid not null references public.profiles (id) on delete cascade,
  client_id uuid not null references public.profiles (id) on delete cascade,
  project_id uuid references public.projects (id) on delete set null,
  amount numeric(10, 2) not null check (amount >= 0),
  currency text not null default 'usd',
  status text not null default 'draft' check (status in ('draft', 'sent', 'paid', 'overdue')),
  -- Processor-neutral on purpose: payments are currently simulated client-side
  -- (see supabase/functions/simulate-payment) rather than run through a real
  -- gateway, but these fields are exactly what a real integration would also
  -- populate, so swapping one in later is a drop-in change.
  payment_ref text,
  payment_transaction_id text,
  -- Set when this invoice was auto-generated by generate_recurring_invoices()
  -- rather than created by hand.
  template_id uuid references public.invoice_templates (id) on delete set null,
  due_date date,
  paid_at timestamptz,
  created_at timestamptz not null default now()
);

create table public.messages (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects (id) on delete cascade,
  sender_id uuid not null references public.profiles (id) on delete cascade,
  body text,
  -- Shares the `attachments` storage bucket/policies with project
  -- receipts/deliverables (already scoped to the project's freelancer+client) —
  -- this just lets a message carry an image, with no separate junction row.
  image_url text,
  created_at timestamptz not null default now(),
  constraint messages_body_or_image_check check (body is not null or image_url is not null)
);

create table public.attachments (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects (id) on delete cascade,
  uploaded_by uuid not null references public.profiles (id) on delete cascade,
  file_url text not null,
  type text not null check (type in ('deliverable', 'receipt')),
  created_at timestamptz not null default now()
);

create table public.subscriptions (
  id uuid primary key default gen_random_uuid(),
  freelancer_id uuid not null unique references public.profiles (id) on delete cascade,
  stripe_subscription_id text,
  plan text not null default 'free' check (plan in ('free', 'pro')),
  status text not null default 'active',
  current_period_end timestamptz
);

-- Denormalized feed the dashboard subscribes to via Realtime. Populated by
-- triggers below so the client never has to compute "what happened" itself.
create table public.activity_events (
  id uuid primary key default gen_random_uuid(),
  freelancer_id uuid not null references public.profiles (id) on delete cascade,
  type text not null check (type in ('invoice_paid', 'invoice_sent', 'new_message', 'project_created', 'milestone_complete')),
  title text not null,
  subtitle text,
  created_at timestamptz not null default now()
);

create index invoices_freelancer_id_idx on public.invoices (freelancer_id);
create index invoices_client_id_idx on public.invoices (client_id);
create index invoices_status_idx on public.invoices (status);
create index projects_freelancer_id_idx on public.projects (freelancer_id);
create index projects_client_id_idx on public.projects (client_id);
create index milestones_project_id_idx on public.milestones (project_id);
create index messages_project_id_idx on public.messages (project_id);
create index attachments_project_id_idx on public.attachments (project_id);
create index activity_events_freelancer_id_idx on public.activity_events (freelancer_id, created_at desc);

-- ---------------------------------------------------------------------------
-- New-user hook: create a profile row from auth signup metadata.
-- The app passes { name, role } as user metadata on supabase.auth.signUp().
-- ---------------------------------------------------------------------------

create function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, role, name, email)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'role', 'client'),
    coalesce(new.raw_user_meta_data ->> 'name', split_part(new.email, '@', 1)),
    new.email
  );
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Trigger firing doesn't depend on the invoking role's grants, so this is
-- safe to lock down — without it, Postgres's default PUBLIC execute grant
-- leaves this SECURITY DEFINER function directly callable via RPC.
revoke execute on function public.handle_new_user() from public, anon, authenticated;

-- ---------------------------------------------------------------------------
-- Activity feed triggers
-- ---------------------------------------------------------------------------

create function public.log_invoice_activity()
returns trigger
language plpgsql
security definer set search_path = public
as $$
declare
  client_name text;
begin
  if tg_op = 'UPDATE' and new.status = 'paid' and old.status is distinct from 'paid' then
    select name into client_name from public.profiles where id = new.client_id;
    insert into public.activity_events (freelancer_id, type, title, subtitle)
    values (new.freelancer_id, 'invoice_paid', 'Invoice paid', client_name || ' paid ' || new.currency || ' ' || new.amount);
  elsif tg_op = 'UPDATE' and new.status = 'sent' and old.status is distinct from 'sent' then
    select name into client_name from public.profiles where id = new.client_id;
    insert into public.activity_events (freelancer_id, type, title, subtitle)
    values (new.freelancer_id, 'invoice_sent', 'Invoice sent', 'Sent to ' || client_name);
  end if;
  return new;
end;
$$;

create trigger on_invoice_status_change
  after update on public.invoices
  for each row execute procedure public.log_invoice_activity();

revoke execute on function public.log_invoice_activity() from public, anon, authenticated;

create function public.log_message_activity()
returns trigger
language plpgsql
security definer set search_path = public
as $$
declare
  proj record;
  sender_name text;
begin
  select p.freelancer_id, p.client_id, p.title into proj
  from public.projects p where p.id = new.project_id;

  select name into sender_name from public.profiles where id = new.sender_id;

  insert into public.activity_events (freelancer_id, type, title, subtitle)
  values (proj.freelancer_id, 'new_message', 'New message', sender_name || ' on ' || proj.title);

  return new;
end;
$$;

create trigger on_message_created
  after insert on public.messages
  for each row execute procedure public.log_message_activity();

revoke execute on function public.log_message_activity() from public, anon, authenticated;

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------

alter table public.profiles enable row level security;
alter table public.freelancer_clients enable row level security;
alter table public.projects enable row level security;
alter table public.milestones enable row level security;
alter table public.invoice_templates enable row level security;
alter table public.invoices enable row level security;
alter table public.messages enable row level security;
alter table public.attachments enable row level security;
alter table public.subscriptions enable row level security;
alter table public.activity_events enable row level security;

-- profiles: everyone can read their own row, plus the counterparties they
-- transact with (a freelancer's clients, and vice versa); only self-update.
-- auth.uid()/is_freelancer() calls throughout this policy section are
-- wrapped in `(select ...)` per Supabase's RLS performance guidance — an
-- unwrapped call gets re-evaluated per row instead of once per query. Purely
-- a perf change; behavior is identical either way.
create policy "profiles_select_self" on public.profiles
  for select using (id = (select auth.uid()));

create policy "profiles_select_counterparty" on public.profiles
  for select using (
    exists (
      select 1 from public.freelancer_clients fc
      where (fc.freelancer_id = (select auth.uid()) and fc.client_id = profiles.id)
         or (fc.client_id = (select auth.uid()) and fc.freelancer_id = profiles.id)
    )
  );

create policy "profiles_update_self" on public.profiles
  for update using (id = (select auth.uid()));

-- RLS's WITH CHECK can only see the proposed new row, not compare it against
-- the old one — so it can't stop a client-role account writing role =
-- 'freelancer' to their own row via profiles_update_self above. Restrict at
-- the privilege layer instead: `authenticated` may only ever touch the
-- columns the app actually lets a user self-edit. `id`, `role`, and `email`
-- are deliberately excluded — email changes go through
-- supabase.auth.updateUser() instead, and role is fixed at signup.
revoke update on public.profiles from authenticated;
grant update (name, avatar_url, push_token, theme, notification_prefs, default_currency) on public.profiles to authenticated;

-- Freelancer-owned tables below check "is_freelancer()" in addition to row
-- ownership, since ownership alone (freelancer_id = auth.uid()) is satisfied
-- by any authenticated user naming themselves as the freelancer — role
-- notwithstanding.
create or replace function public.is_freelancer()
returns boolean
language sql
stable
security definer set search_path = public
as $$
  select exists (select 1 from public.profiles where id = auth.uid() and role = 'freelancer');
$$;

-- RLS policies below call this as `authenticated` (evaluating a policy
-- requires EXECUTE on any function it references), so — unlike the definer
-- functions above — `authenticated` keeps its grant here; only the
-- unauthenticated `anon`/`public` default grant is removed.
revoke execute on function public.is_freelancer() from public, anon;
grant execute on function public.is_freelancer() to authenticated;

-- freelancer_clients
create policy "freelancer_clients_select" on public.freelancer_clients
  for select using (freelancer_id = (select auth.uid()) or client_id = (select auth.uid()));

create policy "freelancer_clients_insert" on public.freelancer_clients
  for insert with check (freelancer_id = (select auth.uid()) and (select public.is_freelancer()));

-- projects
create policy "projects_all_freelancer" on public.projects
  for all using (freelancer_id = (select auth.uid()) and (select public.is_freelancer()))
  with check (freelancer_id = (select auth.uid()) and (select public.is_freelancer()));

create policy "projects_select_client" on public.projects
  for select using (client_id = (select auth.uid()));

-- milestones (scoped through parent project)
create policy "milestones_all_freelancer" on public.milestones
  for all using (
    exists (select 1 from public.projects p where p.id = milestones.project_id and p.freelancer_id = (select auth.uid()))
  ) with check (
    exists (select 1 from public.projects p where p.id = milestones.project_id and p.freelancer_id = (select auth.uid()))
  );

create policy "milestones_select_client" on public.milestones
  for select using (
    exists (select 1 from public.projects p where p.id = milestones.project_id and p.client_id = (select auth.uid()))
  );

-- invoice templates (recurring invoices)
create policy "invoice_templates_all_freelancer" on public.invoice_templates
  for all using (freelancer_id = (select auth.uid()) and (select public.is_freelancer()))
  with check (freelancer_id = (select auth.uid()) and (select public.is_freelancer()));

-- invoices
create policy "invoices_all_freelancer" on public.invoices
  for all using (freelancer_id = (select auth.uid()) and (select public.is_freelancer()))
  with check (freelancer_id = (select auth.uid()) and (select public.is_freelancer()));

create policy "invoices_select_client" on public.invoices
  for select using (client_id = (select auth.uid()));

-- messages: freelancer and client can both read; each can only insert as themself
create policy "messages_select" on public.messages
  for select using (
    exists (
      select 1 from public.projects p
      where p.id = messages.project_id
        and (p.freelancer_id = (select auth.uid()) or p.client_id = (select auth.uid()))
    )
  );

create policy "messages_insert" on public.messages
  for insert with check (
    sender_id = (select auth.uid())
    and exists (
      select 1 from public.projects p
      where p.id = messages.project_id
        and (p.freelancer_id = (select auth.uid()) or p.client_id = (select auth.uid()))
    )
  );

-- attachments: freelancer manages, client can only view
create policy "attachments_all_freelancer" on public.attachments
  for all using (
    exists (select 1 from public.projects p where p.id = attachments.project_id and p.freelancer_id = (select auth.uid()))
  ) with check (
    exists (select 1 from public.projects p where p.id = attachments.project_id and p.freelancer_id = (select auth.uid()))
  );

create policy "attachments_select_client" on public.attachments
  for select using (
    exists (select 1 from public.projects p where p.id = attachments.project_id and p.client_id = (select auth.uid()))
  );

-- subscriptions: freelancer only, own row
create policy "subscriptions_all_freelancer" on public.subscriptions
  for all using (freelancer_id = (select auth.uid()) and (select public.is_freelancer()))
  with check (freelancer_id = (select auth.uid()) and (select public.is_freelancer()));

-- activity_events: freelancer only, own feed, read-only from the client app
-- (rows are written by the SECURITY DEFINER trigger functions above)
create policy "activity_events_select_freelancer" on public.activity_events
  for select using (freelancer_id = (select auth.uid()));

-- ---------------------------------------------------------------------------
-- Storage — receipts and deliverables, one bucket keyed by project id
-- (object path convention: `${project_id}/${filename}`)
-- ---------------------------------------------------------------------------

insert into storage.buckets (id, name, public)
values ('attachments', 'attachments', false)
on conflict (id) do nothing;

create policy "attachments_storage_select" on storage.objects
  for select using (
    bucket_id = 'attachments'
    and exists (
      select 1 from public.projects p
      where p.id::text = (storage.foldername(name))[1]
        and (p.freelancer_id = (select auth.uid()) or p.client_id = (select auth.uid()))
    )
  );

create policy "attachments_storage_insert" on storage.objects
  for insert with check (
    bucket_id = 'attachments'
    and exists (
      select 1 from public.projects p
      where p.id::text = (storage.foldername(name))[1]
        and p.freelancer_id = (select auth.uid())
    )
  );

create policy "attachments_storage_delete" on storage.objects
  for delete using (
    bucket_id = 'attachments'
    and exists (
      select 1 from public.projects p
      where p.id::text = (storage.foldername(name))[1]
        and p.freelancer_id = (select auth.uid())
    )
  );

-- ---------------------------------------------------------------------------
-- Realtime
-- ---------------------------------------------------------------------------

alter publication supabase_realtime add table public.activity_events;
alter publication supabase_realtime add table public.messages;
alter publication supabase_realtime add table public.invoices;

-- ---------------------------------------------------------------------------
-- Recurring invoices — pg_cron turns invoice_templates into real invoices
-- with no server/app needing to be running for it to happen.
-- ---------------------------------------------------------------------------

create or replace function public.generate_recurring_invoices()
returns void
language plpgsql
security definer set search_path = public
as $$
declare
  tmpl record;
  next_date date;
begin
  for tmpl in
    select * from public.invoice_templates
    where active and next_run_date <= current_date
  loop
    insert into public.invoices (freelancer_id, client_id, project_id, amount, currency, status, due_date, template_id)
    values (
      tmpl.freelancer_id,
      tmpl.client_id,
      tmpl.project_id,
      tmpl.amount,
      tmpl.currency,
      'sent',
      current_date + tmpl.due_in_days,
      tmpl.id
    );

    next_date := case tmpl.interval
      when 'weekly' then tmpl.next_run_date + interval '7 days'
      when 'monthly' then tmpl.next_run_date + interval '1 month'
      when 'quarterly' then tmpl.next_run_date + interval '3 months'
      when 'yearly' then tmpl.next_run_date + interval '1 year'
    end;

    update public.invoice_templates set next_run_date = next_date where id = tmpl.id;
  end loop;
end;
$$;

-- Unlike the trigger functions above (return type `trigger`, uncallable outside
-- a trigger), this one returns `void` and is directly callable via RPC — revoke
-- Postgres's default PUBLIC execute grant so only pg_cron/service_role can run it.
revoke execute on function public.generate_recurring_invoices() from public, anon, authenticated;

select cron.schedule(
  'generate-recurring-invoices',
  '0 6 * * *', -- daily at 06:00 UTC
  $$select public.generate_recurring_invoices();$$
);
